# Generated by Django 5.2.1 on 2025-10-10 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0002_alter_categoria_updated_alter_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, espacios, guiones y apóstrofes.', regex="^[A-Za-zÁÉÍÓÚáéíóúÜüÑñ' -]+$")]),
        ),
    ]
