# Generated by Django 5.2.8 on 2025-11-23 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
